### ISSUE TITLE
End to end deployment using docker-compose

### ISSUE THREAD

**Issue by singhalkarun** [BharatSahAIyak/docker-bhasai#4]
- [x] #1 
- [x] #2 
- [x] #3
- [x] #5 
- [x] #7
- [x] #8 @RyanWalker277 
- [x] #10

### Deprioritized
- [x] #11
- [x] #12

## Testing Criteria
- [x] PWA with `botId` env variable

Outcome - `Have a conversation with Admin embedded chat UI`
Output - Demo Video

**Comment by ChakshuGautam** [comment]
- @chinmoy12c to verify FusionAuth
- @RyanWalker277 to update the Vault implementation
