### ISSUE TITLE
Services to be exposed for end user

### ISSUE THREAD

**Issue by singhalkarun** [BharatSahAIyak/docker-bhasai#6]
@Amruth-Vamshi @chinmoy12c can you please confirm what services do I need to expose which end user (bhasai frontend or admin panel directly interacts with)?

1. BFF
2. UserService

Please comment if any other service needs to be exposed.

**Comment by chinmoy12c** [comment]
@singhalkarun Inbound needs to be exposed for communication, as well as uci-apis (only if admin cannot reach it internally otherwise it's not required).

**Comment by singhalkarun** [comment]
> @singhalkarun Inbound needs to be exposed for communication, as well as uci-apis (only if admin cannot reach it internally otherwise it's not required).

Who uses inboundJs for communication?

**Comment by chinmoy12c** [comment]
> > @singhalkarun Inbound needs to be exposed for communication, as well as uci-apis (only if admin cannot reach it internally otherwise it's not required).
> 
> Who uses inboundJs for communication?

It's used by channel webhooks as well as ts.
